server:
  port: 8086

spring:
  devtools:
    restart:
      exclude:  static/**,public/**
      enabled:  true
  redis:
    host: 10.1.175.202
    password: hzzh@2018
    port: 7001
ws:
  server:
    enable: true
    port: 10086
